// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/lishuang/project/daphnis-base-cli-template/node_modules/dumi/dist/client/theme-api/index.js';
