// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/lishuang/project/daphnis-base-cli-template/node_modules/dumi/theme-default/slots/RtlSwitch/index.js';
